/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
    }
    interface DsInput {
    }
    interface DsLabel {
    }
    interface DsSearch {
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLDsLabelElement extends Components.DsLabel, HTMLStencilElement {
    }
    var HTMLDsLabelElement: {
        prototype: HTMLDsLabelElement;
        new (): HTMLDsLabelElement;
    };
    interface HTMLDsSearchElement extends Components.DsSearch, HTMLStencilElement {
    }
    var HTMLDsSearchElement: {
        prototype: HTMLDsSearchElement;
        new (): HTMLDsSearchElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-input": HTMLDsInputElement;
        "ds-label": HTMLDsLabelElement;
        "ds-search": HTMLDsSearchElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
    }
    interface DsInput {
    }
    interface DsLabel {
    }
    interface DsSearch {
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-input": DsInput;
        "ds-label": DsLabel;
        "ds-search": DsSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-input": LocalJSX.DsInput & JSXBase.HTMLAttributes<HTMLDsInputElement>;
            "ds-label": LocalJSX.DsLabel & JSXBase.HTMLAttributes<HTMLDsLabelElement>;
            "ds-search": LocalJSX.DsSearch & JSXBase.HTMLAttributes<HTMLDsSearchElement>;
        }
    }
}
