---
name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    run:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744"
            - uses: "pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598"
              with:
                  version: "latest"
            - uses: "actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - run: "make lint"
            - run: "make test"
            - run: "make build"
